import React from 'react';
import './LegalPage.css';

function TermsOfService() {
  return (
    <div className="legal-page">
      <div className="legal-header">
        <div className="container">
          <h1>Terms of Service</h1>
          <p>Last updated: February 2026</p>
        </div>
      </div>
      <div className="container legal-content">
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using AI Education Suite, you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use our services.</p>
        </section>
        <section>
          <h2>2. Description of Service</h2>
          <p>AI Education Suite provides AI-powered educational tools including essay grading, music lesson generation, quiz creation, reading level analysis, and learning path creation. These tools use artificial intelligence to provide feedback and recommendations.</p>
        </section>
        <section>
          <h2>3. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration. You may not share your account with others.</p>
        </section>
        <section>
          <h2>4. Acceptable Use</h2>
          <p>You agree to use the platform for legitimate educational purposes only. You may not use the service to generate misleading academic work, submit AI-generated content as your own original work without disclosure, or engage in any activity that violates applicable laws.</p>
        </section>
        <section>
          <h2>5. Content Ownership</h2>
          <p>You retain ownership of content you submit to the platform. By using our services, you grant us a limited license to process your content through AI models for the purpose of providing educational feedback.</p>
        </section>
        <section>
          <h2>6. AI-Generated Content</h2>
          <p>Feedback, grades, and recommendations generated by our AI tools are for educational guidance only. They should not be considered as final academic assessments or professional advice.</p>
        </section>
        <section>
          <h2>7. Limitation of Liability</h2>
          <p>AI Education Suite is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of our AI-generated feedback or recommendations.</p>
        </section>
        <section>
          <h2>8. Account Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time through the Settings page.</p>
        </section>
        <section>
          <h2>9. Changes to Terms</h2>
          <p>We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
        </section>
        <section>
          <h2>10. Contact</h2>
          <p>For questions about these terms, contact us through the Contact page or email legal@aieducation.com.</p>
        </section>
      </div>
    </div>
  );
}

export default TermsOfService;
